### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by DHuckaby** [wtekiela/opensub4j#1]
Can you submit this project to maven central please? I would love to not use a .jar.

**Comment by wtekiela** [comment]
The project has been set up for publishing to maven central. I'm waiting for the project to be approved: https://issues.sonatype.org/browse/OSSRH-15700

**Comment by wtekiela** [comment]
Published version 0.1.1
https://oss.sonatype.org/content/repositories/releases/com/github/wtekiela/opensub4j/maven-metadata.xml
