### ISSUE TITLE
Timeout configuration

### ISSUE THREAD

**Issue by danilosimei** [wtekiela/opensub4j#14]
Hi. Is there any way to configure timeout on the requests?

It's very common to opensub has any instability and I noticed that there is no time out exception for these requests.

Thanks in advance.

**Comment by wtekiela** [comment]
@danilosimei was not available before, fixed this by exposing XmlRpcClientConfiguration. It will be possible in the following way:

```
URL url = new URL("https", "api.opensubtitles.org", 443, "/xml-rpc");

XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();
config.setServerURL(url);
config.setConnectionTimeout(1000);
config.setReplyTimeout(1000);
// other configurations ...

OpenSubtitlesClient client = new OpenSubtitlesClientImpl(config);
```

**Comment by wtekiela** [comment]
I will publish this in `0.2.1` shortly

**Comment by danilosimei** [comment]
Thank you very much! :)

**Comment by wtekiela** [comment]
Released: https://repo1.maven.org/maven2/com/github/wtekiela/opensub4j/0.2.1/

**Comment by danilosimei** [comment]
Awesome! Thanks for that! I'm really appreciated.
