### ISSUE TITLE
org.apache.xmlrpc.XmlRpcException

### ISSUE THREAD

**Issue by vinayAryabhat** [wtekiela/opensub4j#20]
URL serverUrl = new URL("https", "api.opensubtitles.org", 443, "/xml-rpc");
OpenSubtitlesClient osClient = new OpenSubtitlesClientImpl(serverUrl);
ServerInfo serverInfo = osClient.serverInfo();  >> here i'm getting   "org.apache.xmlrpc.XmlRpcException: Exception occurred during XML-RPC call"

can you help me to solve this issue ?

**Comment by benjaminsg** [comment]
I've been experiencing this same issue

**Comment by wtekiela** [comment]
Increase logging level to get more information about failures.

**Comment by benjaminsg** [comment]
Lower error seems to be "java.net.ProtocolException: content-length promised 332 bytes, but received 207"

**Comment by wtekiela** [comment]
Again, hard to provide guidance without proper logs and just very generic pieces of information.
Please enable logging and gather DEBUG logs, e.g. via adding dependency to logback:
```
group: 'ch.qos.logback', name: 'logback-classic', version: '1.2.+'
```
and adding `logback.xml` file to your resources. Sample:
```
<configuration>

    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <layout class="ch.qos.logback.classic.PatternLayout">
            <Pattern>
                %d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg\n
            </Pattern>
        </layout>
    </appender>

    <logger name="com.github.wtekiela.opensub4j" level="TRACE" additivity="true">
        <appender-ref ref="CONSOLE"/>
    </logger>

</configuration>
```
