### ISSUE TITLE
username and password

### ISSUE THREAD

**Issue by codesunshine** [wtekiela/opensub4j#21]
Should the username and password be registered in https://www.opensubtitles.org/zh/newuser

**Comment by wtekiela** [comment]
Yes, you need to register using that link (english version: https://www.opensubtitles.org/en/newuser ) and after that you can use those credentials with this library.

Furthermore, you can find more information about opensubtitles' API here: https://trac.opensubtitles.org/projects/opensubtitles 

You might find especially this article useful: https://trac.opensubtitles.org/projects/opensubtitles/wiki/DevReadFirst 

Cheers
