### ISSUE TITLE
Search subtitles with series imdb id, season number and episode number is not correct

### ISSUE THREAD

**Issue by arrajeev87** [wtekiela/opensub4j#24]
When I use the search subtitles method with query and season and episode number I get the proper result however if I pass the series Imdb id instead of query with season and episode numbers I get all subtitle info for the complete series and that particular episode.

I have done the required changes for this in my local branch with some few more fields added in the SubtitleInfo pojo which I would like to have.

I would really appreciate if you can accept these changes.

**Comment by wtekiela** [comment]
Hi @arrajeev87 , can you open a PR for that? Thanks

**Comment by arrajeev87** [comment]
Have opened a pull request.

Thanks

**Comment by arrajeev87** [comment]
Hi @wtekiela need your help to merge the PR.
I am trying to integrate with Open Subtitles and having this changes in place will help me a lot.

Thanks in Advance

**Comment by wtekiela** [comment]
Hi @arrajeev87 
thanks for submitting the PR, will have a look at it this evening CEST

**Comment by wtekiela** [comment]
Fixed in master in #25 and cherry-picked into 0.3 branch in commit 088b53131746c43d1eb2e6e987069f5fc5b48beb

**Comment by wtekiela** [comment]
released 0.3.2 with this improvement
