### ISSUE TITLE
Enhancement Request: Need more information in response on user login

### ISSUE THREAD

**Issue by arrajeev87** [wtekiela/opensub4j#27]
Currently when we login with a user we only get the token back as login response.
However from OpenSubtitles we get a response something like below when we login,
{seconds=0.048, data={UserRank=##, UserNickName=##, UploadCnt=xxx, DownloadCnt=xxx, IsVIP=0, UserWebLanguage=en, IDUser=xxxxx, UserPreferedLanguages=eng}, token=-abcdefgh1234, status=200 OK}

I am interested in the data as well in the login response.

**Comment by wtekiela** [comment]
Implemented in #29 , released in 0.4.0
