### ISSUE TITLE
Support for subtitle encoding

### ISSUE THREAD

**Issue by brunoribeiro** [wtekiela/opensub4j#3]
Non utf-8 subtitles are displayed incorrectly, because the decompress method does not have into account the enconding when converting to string content.

 ã -> ? and etc..

**Comment by wtekiela** [comment]
Latest SNAPSHOT build with this enhancement is available on maven central. Please let me know if it's ok.

**Comment by wtekiela** [comment]
Version 0.1.2 with this improvement has been released.
