### ISSUE TITLE
Subtitles encoding

### ISSUE THREAD

**Issue by LanShunoda** [wtekiela/opensub4j#4]
Is there any way to find out Subtitle encoding? When i get content from subtitle file it is encoded in UTF-8 by default. But some files are in other charsets, and they show incorect. I find that there is method  getContent(String charsetName) . But i dont know charset of downloaded file to encode it correctly.
In response of search subtitles there is field sub encoding (https://trac.opensubtitles.org/projects/opensubtitles/wiki/XMLRPC#DownloadSubtitles).
I cant find in your library it implementation. And i dont know how to add it.

**Comment by LanShunoda** [comment]
I found encoding

**Comment by wtekiela** [comment]
Fixed in: https://github.com/wtekiela/opensub4j/pull/5
