### ISSUE TITLE
downloadSubtitles() returns empty List<SubtitleFile>

### ISSUE THREAD

**Issue by proropoulos** [wtekiela/opensub4j#6]
Hi sir, first of all thanks for your time and your work. Your library really saved me a lot of time for my subtitle managing application.
Although i'd like to note that downloadSubtitles() seems to not work, at least for me. 
I use the 0.1.2 version, can you confirm the issue? 
Thanks

**Comment by wtekiela** [comment]
It **does** work for me both on 0.1.2 and latest snapshot.

What response are you getting when invoking the method? You can see the raw response from the server when you set the `RetriableXmlRpcClient` logger to `DEBUG`.

Also, please note that opensubtitles changed user agent for tests recently - now it's `OSTestUserAgentTemp`.

**Comment by wtekiela** [comment]
Closing due to lack of response. @pror21, please reopen if you still have this issue.
