### ISSUE TITLE
failing to resolve 0.2.0-SNAPSHOT in android studio

### ISSUE THREAD

**Issue by devnullpointer** [wtekiela/opensub4j#7]
Adding dependency as directed in ReadMe and getting a failed to resolve error.

Error:(42, 13) Failed to resolve: com.github.wtekiela:opensub4j:0.2.0-SNAPSHOT

**Comment by wtekiela** [comment]
My bad, forgot to add the snapshot repository definition to the README, will update it shortly.

Try the following repository definitions:

```
repositories {
	maven {
		url 'https://oss.sonatype.org/content/repositories/snapshots/'
	}
	mavenCentral()
}

dependencies {
    compile 'com.github.wtekiela:opensub4j:0.2.0-SNAPSHOT'
}
```

**Comment by wtekiela** [comment]
@devnullpointer should you still have trouble after adding the snapshot repository definition, please reopen this issue.
