### ISSUE TITLE
Cant resolve OpenSubtitlesClient

### ISSUE THREAD

**Issue by UGhari** [wtekiela/opensub4j#8]
I added the dependancy:

`compile 'com.github.wtekiela:opensub4j:0.1.2'`

I then followed the readme and added to my class:

```
public class Subtitles {
    public Subtitles(){
        URL serverUrl = new URL("https", "api.opensubtitles.org", 443, "/xml-rpc");
        OpenSubtitlesClient osClient = new OpenSubtitlesClientImpl(serverUrl);
    }
}

```

But i get the error:

> Cant resolve symbol OpenSubtitlesClient.

and there is no way to import it

**Comment by wtekiela** [comment]
Hi @UGhari 

The library is still in its early versions and between versions 0.1.2 and 0.2.0 I did some refactorings. To use it like in the readme, you need to use the latest 0.2.0-SNAPSHOT version, like this:

```
repositories {
	maven {
		url 'https://oss.sonatype.org/content/repositories/snapshots/'
	}
	mavenCentral()
}

dependencies {
    compile 'com.github.wtekiela:opensub4j:0.2.0-SNAPSHOT'
}
```

I will update the readme to reflect that information.

**Comment by UGhari** [comment]
ah cool thanks,
I have another very stupid question for you, not related to your lib

`osClient.login("username", "password", "en", "TemporaryUserAgent");`

Where do i create a user and pass on opensubtitles to work with this method? I cant seem to find it
