### ISSUE TITLE
not getting subtitleInfo.getId()

### ISSUE THREAD

**Issue by 24Lathiya** [wtekiela/opensub4j#9]
how to get subtitleInfo.getId() as mention in Download subtitle section.

**Comment by wtekiela** [comment]
@24Lathiya make sure you are using 0.2.0-SNAPSHOT - that section refers to the latest version: https://github.com/wtekiela/opensub4j/blob/aea6fb95163b9c1e5d672cf64a9cc48898a57086/src/main/java/com/github/wtekiela/opensub4j/response/SubtitleInfo.java#L64

**Comment by wtekiela** [comment]
@24Lathiya version 0.2.0 has been released which also contains the mentioned method.
